/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import clase.Departamento;
import clase.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import practica4_ejercicio1.Practica4_Ejercicio1;

/**
 *
 * @author Angel
 */
public class Formulario extends javax.swing.JFrame {
    
    private static String accion = "A";
            
    public Formulario() {
        initComponents();
        //centrar ventana
        setLocationRelativeTo(null);
        inicializaCombobox();
    }
    public Formulario(Trabajador n_emple){
        this();
        cargaFormulario(n_emple);
        accion = "M";
    }
    
    private void inicializaCombobox(){
        ArrayList<Departamento> listaDept = Practica4_Ejercicio1.dameDepartamentos();
        for(int x = 0; x<listaDept.size(); x++){
            this.jcbdepartamento.insertItemAt(listaDept.get(x).getNombre(), x);
        }
        
        ArrayList<Contrato> listaCont = Practica4_Ejercicio1.dameContratos();
        for(int x = 0; x<listaCont.size(); x++){
            this.jcbcontrato.insertItemAt(listaCont.get(x).getNombre(), x);
        }
    }
    
    private void cargaFormulario(Trabajador t){
        this.jtnumemp.setText(t.getN_emple());
        this.jtdireccion.setText(t.getDireccion());
        this.jTDni.setText(t.getDni());
        this.jtapellido.setText(t.getApellido());
        this.jtfecha.setText(t.getFechaAlta().toString());
        this.jtnombre.setText(t.getNombre());
        this.jtnss.setText(t.getNss());
        this.jttelefono.setText(t.getTelefono());
        if (t.getSexo().equals("H")) {
            this.jrbhombre.setSelected(true);
        }
        else{
            this.jrbmujer.setSelected(true);
        }
        if (t.getEstadoCivil().equals("S")) {
            this.jrbsoltero.setSelected(true);
        }
        else{
            this.jrbcasado.setSelected(true);
        }
        this.jcbcontrato.setSelectedIndex(Integer.parseInt(t.getContrato().getId())-1);
        this.jcbdepartamento.setSelectedIndex(Integer.parseInt(t.getDepartamento().getId())-1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gSexo = new javax.swing.ButtonGroup();
        gEstadoCivil = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbaceptar = new javax.swing.JButton();
        jbcancelar = new javax.swing.JButton();
        jtnss = new javax.swing.JTextField();
        jtapellido = new javax.swing.JTextField();
        jtnombre = new javax.swing.JTextField();
        jTDni = new javax.swing.JTextField();
        jtdireccion = new javax.swing.JTextField();
        jttelefono = new javax.swing.JTextField();
        jtnumemp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jrbhombre = new javax.swing.JRadioButton();
        jrbmujer = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jrbsoltero = new javax.swing.JRadioButton();
        jrbcasado = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jcbdepartamento = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jcbcontrato = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jtfecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DNI:");

        jLabel2.setText("NSS");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Direccion:");

        jLabel5.setText("Apellido:");

        jLabel6.setText("Telefono:");

        jLabel7.setText("Nº empleado:");

        jbaceptar.setText("Aceptar");
        jbaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbaceptarActionPerformed(evt);
            }
        });

        jbcancelar.setText("Cancelar");
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });

        jtnss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnssActionPerformed(evt);
            }
        });

        jtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtapellidoActionPerformed(evt);
            }
        });

        jtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnombreActionPerformed(evt);
            }
        });

        jTDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDniActionPerformed(evt);
            }
        });

        jtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtdireccionActionPerformed(evt);
            }
        });

        jttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jttelefonoActionPerformed(evt);
            }
        });

        jtnumemp.setEnabled(false);
        jtnumemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnumempActionPerformed(evt);
            }
        });

        jLabel8.setText("Sexo");

        gSexo.add(jrbhombre);
        jrbhombre.setText("Hombre");

        gSexo.add(jrbmujer);
        jrbmujer.setText("Mujer");
        jrbmujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbmujerActionPerformed(evt);
            }
        });

        jLabel9.setText("Estado civil");

        gEstadoCivil.add(jrbsoltero);
        jrbsoltero.setText("soltero");

        gEstadoCivil.add(jrbcasado);
        jrbcasado.setText("casado");

        jLabel10.setText("Tipo de contrato");

        jcbdepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbdepartamentoActionPerformed(evt);
            }
        });

        jLabel11.setText("Departamento");

        jLabel12.setText("Fecha de Alta");

        jtfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbcontrato, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtapellido))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtdireccion))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtnombre))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jtnss))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTDni))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jttelefono)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jrbhombre)
                                            .addGap(18, 18, 18)
                                            .addComponent(jrbmujer))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jrbsoltero)
                                            .addGap(22, 22, 22)
                                            .addComponent(jrbcasado)))
                                    .addGap(0, 15, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtnumemp, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtfecha))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(jcbdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 15, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jbaceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(jbcancelar)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtnss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jrbhombre)
                    .addComponent(jrbmujer))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrbsoltero)
                        .addComponent(jrbcasado))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbcontrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtnumemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbaceptar)
                    .addComponent(jbcancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed
        Practica4_Ejercicio1.returnToVentanaPrincipal();
    }//GEN-LAST:event_jbcancelarActionPerformed

    private void jtnssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtnssActionPerformed

    private void jtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtapellidoActionPerformed

    private void jtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtnombreActionPerformed

    private void jTDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDniActionPerformed

    private void jtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtdireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtdireccionActionPerformed

    private void jttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jttelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jttelefonoActionPerformed

    private void jtnumempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnumempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtnumempActionPerformed

    private void jrbmujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbmujerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbmujerActionPerformed

    private void jtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfechaActionPerformed

    private void jbaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbaceptarActionPerformed
        String dni = this.jTDni.getText();
        String nss = this.jtnss.getText();
        String nombre = this.jtnombre.getText();
        String apellido = this.jtapellido.getText();
        String direccion = this.jtdireccion.getText();
        String telefono = this.jttelefono.getText();
        String fechaAlta = this.jtfecha.getText();
        int departamento = this.jcbdepartamento.getSelectedIndex();
        int contrato = this.jcbcontrato.getSelectedIndex();
        String sexo;
        if (jrbhombre.isSelected()) {
            sexo = "H";
        }
        else{
            sexo= "M";
        }
        String estadocivil;
        if (jrbsoltero.isSelected()) {
            estadocivil= "S";
        }
        else{
            estadocivil="C";
        }
        
        
        if (accion.equals("A")) {
            Practica4_Ejercicio1.altatrabajador(dni,nss,nombre,apellido,direccion,telefono,fechaAlta,departamento,contrato,sexo,estadocivil);
        }
        else{
            String n_emple=jtnumemp.getText();
            Practica4_Ejercicio1.modificartrabajador(dni,nss,nombre,apellido,direccion,telefono,fechaAlta,departamento,contrato,sexo,estadocivil,n_emple);
        }
        
    }//GEN-LAST:event_jbaceptarActionPerformed

    private void jcbdepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbdepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbdepartamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup gEstadoCivil;
    private javax.swing.ButtonGroup gSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTDni;
    private javax.swing.JButton jbaceptar;
    private javax.swing.JButton jbcancelar;
    private javax.swing.JComboBox jcbcontrato;
    private javax.swing.JComboBox jcbdepartamento;
    private javax.swing.JRadioButton jrbcasado;
    private javax.swing.JRadioButton jrbhombre;
    private javax.swing.JRadioButton jrbmujer;
    private javax.swing.JRadioButton jrbsoltero;
    private javax.swing.JTextField jtapellido;
    private javax.swing.JTextField jtdireccion;
    private javax.swing.JTextField jtfecha;
    private javax.swing.JTextField jtnombre;
    private javax.swing.JTextField jtnss;
    private javax.swing.JTextField jtnumemp;
    private javax.swing.JTextField jttelefono;
    // End of variables declaration//GEN-END:variables

    
}
