
package Vista;

import Controlador.Control;
import Modelo.Evento;
import javax.swing.JOptionPane;


public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmianadirevento = new javax.swing.JMenuItem();
        jmieliminar = new javax.swing.JMenuItem();
        jmimodificar = new javax.swing.JMenuItem();
        jmsalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Empresa ......");

        jMenu1.setText("Opciones");

        jmianadirevento.setText("añadir evento");
        jmianadirevento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmianadireventoActionPerformed(evt);
            }
        });
        jMenu1.add(jmianadirevento);

        jmieliminar.setText("Eliminar evento");
        jmieliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmieliminarActionPerformed(evt);
            }
        });
        jMenu1.add(jmieliminar);

        jmimodificar.setText("Modificar evento");
        jmimodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmimodificarActionPerformed(evt);
            }
        });
        jMenu1.add(jmimodificar);

        jMenuBar1.add(jMenu1);

        jmsalir.setText("Salir");
        jmsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmsalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmsalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmianadireventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmianadireventoActionPerformed
        Control.ventanaAnadir();
    }//GEN-LAST:event_jmianadireventoActionPerformed

    private void jmsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmsalirMouseClicked
        Control.finPrograma();
    }//GEN-LAST:event_jmsalirMouseClicked

    private void jmieliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmieliminarActionPerformed
        Control.ventanaEliminar();
    }//GEN-LAST:event_jmieliminarActionPerformed

    private void jmimodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmimodificarActionPerformed
        String nombreM = JOptionPane.showInputDialog(this,"Indica el nombre del evento.");
        Evento encontrado=Control.updateEvento(nombreM);
        if (encontrado==null) {
            JOptionPane.showMessageDialog(this, "Evento no encontrado.");
        }
        else{
            //añadir a ventana addevento los datos y guardar la modificacion
        }
    }//GEN-LAST:event_jmimodificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmianadirevento;
    private javax.swing.JMenuItem jmieliminar;
    private javax.swing.JMenuItem jmimodificar;
    private javax.swing.JMenu jmsalir;
    // End of variables declaration//GEN-END:variables
}
